name: front
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-266.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
 
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  animated_splash_screen: ^1.3.0
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.2.2
  font_awesome_flutter: ^10.4.0

  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  geocode: ^1.0.2
  jwt_decode: ^0.3.1
  flutter_stripe: ^9.2.0
  flutter_paypal: ^0.0.8
  image_picker: ^0.8.7+5
  intl_phone_number_input: ^0.7.3+1
  web_socket_channel: ^2.4.0
  http_parser: ^4.0.2
  file_picker: ^5.3.1
  socket_io_client: ^2.0.2
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
   
    - family: Pecita
      fonts:
        - asset: fonts/Pecita-Regular.ttf
  

